name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image to deploy'
        required: true
        default: 'latest'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.8.0'
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure kubectl
      run: |
        aws eks --region ${{ secrets.AWS_EKS_REGION }} update-kubeconfig --name eks

    - name: Add Helm repository
      run: helm repo add matheusfm https://matheusfm.dev/charts 
      
    - name: Upgrade Helm chart
      run: |
        helm upgrade httpbin --set service.type=NodePort --set image.repository=872515294445.dkr.ecr.eu-west-1.amazonaws.com/itamar --set image.tag=${{ github.event.inputs.image-tag }} -n httpbin-custom matheusfm/httpbin
