# .github/workflows/Terraform-deploy.yml
name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5 

    - name: Terraform Init
      run: terraform init
      working-directory: Terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: Terraform
